### ISSUE TITLE
Create convenience method for handle_opts pattern

### ISSUE THREAD

**Issue by bbriggs** [Legobot/Legobot#165]
Most legos has a common hande_opts pattern [like so](https://github.com/Legobot/legos.net-tools/blob/f55668b99d4e11e65aadc697948f17e942466c00/legos/nettools.py#L32)

```python
    def _handle_opts(self, message):
        try:
            target = message['metadata']['source_channel']
            opts = {'target': target}
        except IndexError:
            opts = None
            logger.error('''Could not identify message source in message:
                                    {}'''.format(str(message)))
```

We should create a convenience method that builds a reply message automatically.

**Comment by nickjriley** [comment]
I've drafted an implementation for this. Just need to test it.

**Comment by nickjriley** [comment]
Just to be certain we are on the same page here, the output of this method would be `{'target': '#source-channel'}` or a new `Message` object?

**Comment by drewpearce** [comment]
The former. In the example that Bren posted, the var called `opts` would be returned. This is what the convenience method needs to provide.
